language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

branches:
  only:
    - /^6\.0\.[0-9]*$/

before_install:
  - source ci/obs_common.sh
  - source ci/obs_before_install.sh

before_script:
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update -qq
  - sudo apt-get install -qq devscripts equivs
  - sudo mk-build-deps -i -r -t " apt-get --no-install-recommends --yes"

script:
  - ./autogen.sh
  - ./configure --prefix=$HOME
  - make
  - source ci/obs_prepare.sh

after_success:
  - source ci/obs_common.sh
  - source ci/obs_commit.sh

env:
  global:
    - secure: "PQgMMu9MKGqFxcSnO9TmhCt00WV/p5/5l9CUxkkSt64AjbQpjg8S1zchmZ9k/M6bvk4Oa6TlGFypP8mLLFC2SGap/uWQxxNPGOfQalFex3nBt8szl6ELz4p2sR3EaFpuAU092+bVNAboN3sdPJ/cqfpb4mxynu58+ShwOqGL/dIrjo1kjWM0087MBXRHHBeH9cUpDHMQKnvyt9gEL85jY/pXrUOJo0jzCBb9l1FGClCzKmdIdaYLUifn/H5oMzIXWnLK6sSjeLhKeEuIvRbZI0GkG7PLg9bdfLk6HrZX8jYxJE4Ao9GAJ5x5PZ4KtALpqgt0PS8oB7NVOzRk2fNgV1FUZ+dCaEyRTCzSYZe9LRpPSMLKCYATSqkebGxKxR8hM9Aunu2nMEEbHLwkTBVB97TMRgTqeyMWr3vKq2PbaaP9rBayH6qZKP9QYFvx6QaXcSpzch21sfV2y1vJW5JyQE2bsaQbqcszi497jh8ELO1ZyVeQS6BUTb03+RNUVmskgYRDVkVHYDqEmFdKFdQjmPa6GZkdias/EG+JsG5C9SFezHn5Kzv8S8CMzmoDN7X1nq0Z09lEErfgKHzXqVjja9jNTeZSNUHEmfZbzH2nHC8s14gbl1FQgl9m90ChpjMMHQCa7lOgW4qxTCFUzXgfPTaYGc+bDQ7zZSEWp+FTidw="
    - OBS_HOME=security
    - OBS_PROJECT=Zorp
    - OBS_MAJOR_VERSION=6
    - OBS_MINOR_VERSION=0
    - OBS_MAINTENANCE_VERSION=10
    - OBS_PACKAGE=zorp
